
---
title: "Scooby-Doo - Check Box"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
    logo: logo.png
    source_code: embed
    social: menu

runtime: shiny
---

```{r global, include=FALSE}
# load data in 'global' chunk so it can be shared by all users of the dashboard
library(flexdashboard)
library(tidyverse)
library(plotly)
library(knitr)
library(DT)
library(lubridate)
df <- read_csv('ScoobyDoo.csv')
df$date <- mdy(df$dateAired)
df$mainMonsterGender = factor(df$mainMonsterGender)
df$moster.amount = factor(df$monster.amount)
df$jeepers = factor(df$jeepers)
```

{.sidebar}
=======================================================================

Every Scooby-Doo episode and movie's various variables.

Took ~1 year to watch every Scooby-Doo iteration and track every variable. Many values are subjective by nature of watching but I tried my hardest to keep the data collection consistent.

Select the input for the plots. 

```{r}
dateRangeInput(inputId = "date_input", 
               label = h2("Date range"), 
               start = min(df$date), 
               end = max(df$date),
               min = min(df$date), 
               max = max(df$date))
```

Main Tab 1
=======================================================================

Column {data-width=500}
-----------------------------------------------------------------------

### Density Plot

```{r}
renderPlotly({
  p1 <- df %>% 
    filter(date > input$date_input[1], date < input$date_input[2]) %>% 
    ggplot(aes(x=monster.amount, color=jeepers))+
    geom_density()
  ggplotly(p1)
})
```

Column {data-width=500}
-----------------------------------------------------------------------

### Bar Plot

```{r}
renderPlotly({
  p2 <- df %>% 
    filter(date > input$date_input[1], date < input$date_input[2]) %>% 
    ggplot(aes(x=monster.amount, fill=mainMonsterGender))+
    geom_bar()
  ggplotly(p2)
})
```
